services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - upload-data:/app/data/uploads
      - db-data:/app/data
    restart: unless-stopped

volumes:
  upload-data:
  db-data:
